name: Dart Data Structures & Algorithms CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Format Check
        run: dart format lib --set-exit-if-changed --output=none --show=changed --summary=none
      - name: Run tests
        run: pub run test
