name: Dart Data Structures & Algorithms CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: dart:3-sdk

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub get
      - name: Format Check
        run: dart format lib test --set-exit-if-changed --output=none
      - name: Run tests
        run: dart run test
